#ifndef GUIC_SETTINGS_HPP
#define GUIC_SETTINGS_HPP

#define GUIC_MAX_MLTITLE_LENGHT 300
#define GUIC_MAX_MLTITLE_ROWS 100

#define GUIC_MAX_LIST_ITEMS 100
#define GUIC_MAX_ITEMS 10000
#define GUIC_BASE_LIST_INTERVAL 5
#define GUIC_BASE_LIST_TAB 5
#define GUIC_BASE_BUTTON_FRAMEFAT 4
#define GUIC_BASE_ENTER_INTERVAL 5

#define GUIC_BASE_CHAR_SIZE 15

#define GUIC_MAX_LAYER 6

#define GUIC_BASE_HIGH_LAYER 0
#define GUIC_BASE_CONTAINER_LAYER 0
#define GUIC_BASE_INTERFACE_LAYER 1
#define GUIC_BASE_LIST_LAYER 2
#define GUIC_BASE_ENTER_LAYER 3
#define GUIC_BASE_MLTITLE_LAYER 4
#define GUIC_BASE_BUTTON_LAYER 5
#define GUIC_BASE_TITLE_LAYER 6

#endif
